const $=s=>document.querySelector(s);
function msg(el,text,ok=false){if(el){el.textContent=text;el.style.color=ok?'#1f6b54':'#9b3a34';}}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opts.headers||{})},credentials:'same-origin',...opts});let d={};try{d=await r.json();}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d;}
async function submitAppraisal(e){e.preventDefault();const out=$('#appraisalStatus');try{const data=Object.fromEntries(new FormData(e.target));await api('/api/appraisals',{method:'POST',body:JSON.stringify(data)});e.target.reset();msg(out,'Thank you. Your appraisal request has been received.',true);}catch(err){msg(out,err.message);}}
async function loadJobs(){const target=$('#jobsList');if(!target)return;try{const data=await api('/api/jobs');if(!data.length){target.innerHTML='<div class="empty">There are no open positions right now.</div>';return;}target.innerHTML=data.map(j=>`<article class="job-card"><div><span>${esc(j.department||'Bloomtide')}</span><h3>${esc(j.title)}</h3><p>${esc(j.location||'United States')} · ${esc(j.employment_type||'Full-time')}</p></div><button class="apply-btn" data-id="${j.id}" data-title="${esc(j.title)}">Apply</button></article>`).join('');document.querySelectorAll('.apply-btn').forEach(b=>b.onclick=()=>openApply(b.dataset.id,b.dataset.title));}catch(err){target.innerHTML=`<div class="empty">${esc(err.message)}</div>`;}}
function openApply(id,title){$('#job_id').value=id;$('#jobTitle').textContent=title;$('#applyPanel').hidden=false;$('#applyPanel').scrollIntoView({behavior:'smooth'});}
async function submitApplication(e){e.preventDefault();const out=$('#applicationStatus');try{const data=Object.fromEntries(new FormData(e.target));await api('/api/applications',{method:'POST',body:JSON.stringify(data)});e.target.reset();$('#applyPanel').hidden=true;msg(out,'Application submitted successfully.',true);}catch(err){msg(out,err.message);}}
async function adminLogin(e){e.preventDefault();const out=$('#loginStatus');try{const data=Object.fromEntries(new FormData(e.target));await api('/api/admin/login',{method:'POST',body:JSON.stringify(data)});location.reload();}catch(err){msg(out,err.message);}}
async function adminLogout(){try{await api('/api/admin/logout',{method:'POST'});}finally{location.reload();}}
async function loadAdmin(){if(!$('#adminApp'))return;try{const s=await api('/api/admin/session');if(!s.authenticated){$('#loginCard').hidden=false;return;}$('#loginCard').hidden=true;$('#dashboard').hidden=false;await Promise.all([loadRequests(),loadAdminJobs(),loadApplications()]);}catch(err){$('#loginCard').hidden=false;msg($('#loginStatus'),err.message);}}
async function loadRequests(){const data=await api('/api/admin/appraisals');const el=$('#requestsBody');$('#requestCount').textContent=data.length;el.innerHTML=data.map(r=>`<tr><td>${esc(r.name)}<br><small>${esc(r.email)}</small></td><td>${esc(r.property_address)}</td><td>${esc(r.property_type||'')}</td><td><select data-request-status="${r.id}">${['new','contacted','inspection_scheduled','in_progress','report_ready','completed'].map(s=>`<option ${s===r.status?'selected':''} value="${s}">${s.replaceAll('_',' ')}</option>`).join('')}</select></td><td><input class="fee" data-request-fee="${r.id}" type="number" step="0.01" min="0" value="${r.fee??''}" placeholder="Set fee"></td><td><button data-save-request="${r.id}">Save</button></td></tr>`).join('');document.querySelectorAll('[data-save-request]').forEach(b=>b.onclick=()=>saveRequest(b.dataset.saveRequest));}
async function saveRequest(id){const status=document.querySelector(`[data-request-status="${id}"]`).value;const fee=document.querySelector(`[data-request-fee="${id}"]`).value;try{await api(`/api/admin/appraisals/${id}`,{method:'PATCH',body:JSON.stringify({status,fee})});alert('Request updated');}catch(err){alert(err.message);}}
async function saveJob(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.published=d.published==='on';try{await api('/api/admin/jobs',{method:'POST',body:JSON.stringify(d)});e.target.reset();await loadAdminJobs();alert('Job saved');}catch(err){alert(err.message);}}
async function loadAdminJobs(){const data=await api('/api/admin/jobs');const el=$('#jobsBody');$('#jobCount').textContent=data.length;el.innerHTML=data.map(j=>`<tr><td>${esc(j.title)}</td><td>${esc(j.location||'')}</td><td>${j.published?'Published':'Draft'}</td><td>${new Date(j.created_at).toLocaleDateString()}</td><td><button data-toggle-job="${j.id}" data-current="${j.published}">${j.published?'Unpublish':'Publish'}</button></td></tr>`).join('');document.querySelectorAll('[data-toggle-job]').forEach(b=>b.onclick=()=>toggleJob(b.dataset.toggleJob,b.dataset.current==='true'));}
async function toggleJob(id,current){try{await api(`/api/admin/jobs/${id}`,{method:'PATCH',body:JSON.stringify({published:!current})});loadAdminJobs();}catch(err){alert(err.message);}}
async function loadApplications(){const data=await api('/api/admin/applications');const el=$('#applicationsBody');$('#applicationCount').textContent=data.length;el.innerHTML=data.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.job_title||'')}</td><td><a href="mailto:${encodeURIComponent(a.email)}">${esc(a.email)}</a></td><td>${esc(a.phone||'')}</td><td>${esc(a.status)}</td></tr>`).join('');}
document.addEventListener('DOMContentLoaded',()=>{const fp=$('.founder-photo');if(fp)fp.style.backgroundImage="url('assets/charles-robinson.svg')";$('#appraisalForm')?.addEventListener('submit',submitAppraisal);$('#applicationForm')?.addEventListener('submit',submitApplication);$('#adminLogin')?.addEventListener('submit',adminLogin);$('#jobForm')?.addEventListener('submit',saveJob);$('#logoutBtn')?.addEventListener('click',adminLogout);loadJobs();loadAdmin();});
