const cfg=window.BLOOMTIDE_CONFIG||{};
const configured=cfg.supabaseUrl&&cfg.supabaseAnonKey&&!cfg.supabaseUrl.includes('YOUR_');
const sb=configured?supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
const $=s=>document.querySelector(s);
function msg(el,text,ok=false){if(el){el.textContent=text;el.style.color=ok?'#1f6b54':'#9b3a34';}}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
async function submitAppraisal(e){e.preventDefault();const out=$('#appraisalStatus');if(!configured)return msg(out,'Database setup is not connected yet. Add the Supabase project details in config.js.');const data=Object.fromEntries(new FormData(e.target));const {error}=await sb.from('appraisal_requests').insert([{...data,status:'new'}]);if(error)return msg(out,error.message);e.target.reset();msg(out,'Thank you. Your appraisal request has been received.',true);}
async function loadJobs(){const target=$('#jobsList');if(!target)return;if(!configured){target.innerHTML='<div class="empty">Careers database connection is being configured.</div>';return;}const {data,error}=await sb.from('jobs').select('*').eq('published',true).order('created_at',{ascending:false});if(error){target.textContent=error.message;return;}if(!data.length){target.innerHTML='<div class="empty">There are no open positions right now.</div>';return;}target.innerHTML=data.map(j=>`<article class="job-card"><div><span>${esc(j.department||'Bloomtide')}</span><h3>${esc(j.title)}</h3><p>${esc(j.location||'United States')} · ${esc(j.employment_type||'Full-time')}</p></div><button class="apply-btn" data-id="${j.id}" data-title="${esc(j.title)}">Apply</button></article>`).join('');document.querySelectorAll('.apply-btn').forEach(b=>b.onclick=()=>openApply(b.dataset.id,b.dataset.title));}
function openApply(id,title){$('#job_id').value=id;$('#jobTitle').textContent=title;$('#applyPanel').hidden=false;$('#applyPanel').scrollIntoView({behavior:'smooth'});}
async function submitApplication(e){e.preventDefault();const out=$('#applicationStatus');if(!configured)return msg(out,'Database setup is not connected yet.');const data=Object.fromEntries(new FormData(e.target));const {error}=await sb.from('job_applications').insert([{...data,status:'new'}]);if(error)return msg(out,error.message);e.target.reset();$('#applyPanel').hidden=true;msg(out,'Application submitted successfully.',true);}
async function adminLogin(e){e.preventDefault();const out=$('#loginStatus');if(!configured)return msg(out,'Add Supabase credentials to config.js first.');const data=Object.fromEntries(new FormData(e.target));const {error}=await sb.auth.signInWithPassword({email:data.email,password:data.password});if(error)return msg(out,error.message);location.reload();}
async function adminLogout(){if(sb){await sb.auth.signOut();location.reload();}}
async function loadAdmin(){if(!$('#adminApp'))return;if(!configured){$('#loginCard').hidden=false;$('#loginCard').innerHTML='<h2>Connect the database</h2><p>Bloomtide is ready for Supabase. Follow SETUP.md, then add the project URL and anon key to config.js.</p>';return;}const {data:{session}}=await sb.auth.getSession();if(!session){$('#loginCard').hidden=false;return;}$('#loginCard').hidden=true;$('#dashboard').hidden=false;await Promise.all([loadRequests(),loadAdminJobs(),loadApplications()]);}
async function loadRequests(){const {data,error}=await sb.from('appraisal_requests').select('*').order('created_at',{ascending:false});const el=$('#requestsBody');if(error){el.innerHTML=`<tr><td colspan="6">${esc(error.message)}</td></tr>`;return;}$('#requestCount').textContent=data.length;el.innerHTML=data.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.property_address)}</td><td>${esc(r.property_type)}</td><td><select data-request-status="${r.id}">${['new','contacted','inspection_scheduled','in_progress','report_ready','completed'].map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select></td><td><input class="fee" data-request-fee="${r.id}" type="number" step="0.01" value="${r.fee??''}" placeholder="Set fee"></td><td><button data-save-request="${r.id}">Save</button></td></tr>`).join('');document.querySelectorAll('[data-save-request]').forEach(b=>b.onclick=()=>saveRequest(b.dataset.saveRequest));}
async function saveRequest(id){const status=document.querySelector(`[data-request-status="${id}"]`).value;const fee=document.querySelector(`[data-request-fee="${id}"]`).value||null;const {error}=await sb.from('appraisal_requests').update({status,fee}).eq('id',id);alert(error?error.message:'Request updated');}
async function saveJob(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.published=d.published==='on';const {error}=await sb.from('jobs').insert([d]);if(error)return alert(error.message);e.target.reset();await loadAdminJobs();alert('Job saved');}
async function loadAdminJobs(){const {data,error}=await sb.from('jobs').select('*').order('created_at',{ascending:false});const el=$('#jobsBody');if(error){el.innerHTML=`<tr><td colspan="5">${esc(error.message)}</td></tr>`;return;}$('#jobCount').textContent=data.length;el.innerHTML=data.map(j=>`<tr><td>${esc(j.title)}</td><td>${esc(j.location||'')}</td><td>${j.published?'Published':'Draft'}</td><td>${new Date(j.created_at).toLocaleDateString()}</td><td><button data-toggle-job="${j.id}" data-current="${j.published}">${j.published?'Unpublish':'Publish'}</button></td></tr>`).join('');document.querySelectorAll('[data-toggle-job]').forEach(b=>b.onclick=()=>toggleJob(b.dataset.toggleJob,b.dataset.current==='true'));}
async function toggleJob(id,current){const {error}=await sb.from('jobs').update({published:!current}).eq('id',id);if(error)alert(error.message);else loadAdminJobs();}
async function loadApplications(){const {data,error}=await sb.from('job_applications').select('*,jobs(title)').order('created_at',{ascending:false});const el=$('#applicationsBody');if(error){el.innerHTML=`<tr><td colspan="5">${esc(error.message)}</td></tr>`;return;}$('#applicationCount').textContent=data.length;el.innerHTML=data.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.jobs?.title||'')}</td><td><a href="mailto:${encodeURIComponent(a.email)}">${esc(a.email)}</a></td><td>${esc(a.phone||'')}</td><td>${esc(a.status)}</td></tr>`).join('');}
document.addEventListener('DOMContentLoaded',()=>{$('#appraisalForm')?.addEventListener('submit',submitAppraisal);$('#applicationForm')?.addEventListener('submit',submitApplication);$('#adminLogin')?.addEventListener('submit',adminLogin);$('#jobForm')?.addEventListener('submit',saveJob);$('#logoutBtn')?.addEventListener('click',adminLogout);loadJobs();loadAdmin();});